# wrangler.toml
name = 'tiancaizhaozhao'
main = "_worker.js"
compatibility_date = "2025-12-05"
keep_vars = true

[vars]
UUID = "48221544-7890-4886-9052-162391696205"

PROXYIP = "ProxylPSG.CMLiussss.net"

ADDAPI = """
https://addressesapi.090227.xyz/cmcc-ipv6
https://addressesapi.090227.xyz/ct
https://addressesapi.090227.xyz/cmcc"""

# 本地优选 IP 列表
ADD = """
[2400:cb00:f00e:a8:5d:c71d:2c71:7c63]
[2803:f800:50:0:d6ce:3a6:7088:f992]
[2803:f800:51::f49d:b305:cbc7]
[2803:f800:51::84f0:bd51:326a]"""

ADMIN = "zhaozhao"

[[kv_namespaces]]
binding = "KV"
id = "d76a0189bf4f498c9912322ef78388ff"






